export const base_columns = [{
        title:"状态",
        dataIndex:"status",
        key:"status",
        render: (txt)=>window.ENUM.getEnum("status", txt+'')
    },{
        title:"类别",
        dataIndex:"type",
        key:"type",
        render: (txt)=>window.ENUM.getEnum("baseDataType", txt+'')
    },{
        title:"创建人",
        dataIndex:"createByName",
        key:"createByName"
    },{
        title:"创建时间",
        dataIndex:"createDate",
        key:"createDate"
    },{
        title:"更新人",
        dataIndex:"updateByName",
        key:"updateByName"
    },{
        title:"更新时间",
        dataIndex:"updateDate",
        key:"updateDate"
    }
];
//数据字典
let dataDic = [
    {cn:"民族", en:"category",code:"C001"},
    {cn:"性别", en:"category",code:"C002"},
    {cn:"语言", en:"category",code:"C003"},
    {cn:"婚姻状态", en:"category",code:"C004"},
    {cn:"证件类型", en:"category",code:"C005"},
    {cn:"任职类型", en:"category",code:"C006"},
    {cn:"血型", en:"category",code:"C007"},
    {cn:"在职状态", en:"category",code:"C008"},
    {cn:"学历", en:"category",code:"C009"},
    {cn:"库存状态", en:"category",code:"C010"},
    {cn:"业务类型", en:"category",code:"C011"},
    {cn:"支付条款", en:"category",code:"C012",isManage:1},
    {cn:"收付款条件", en:"category",code:"C013"},
    {cn:"收付款方式", en:"category",code:"C014",isManage:1},
    {cn:"行业", en:"category",code:"C015"},
    {cn:"公司规模", en:"category",code:"C016"},
    {cn:"公司类别", en:"category",code:"C017"},
    {cn:"公司性质", en:"category",code:"C018"},
    {cn:"经营类型", en:"category",code:"C019"},
    {cn:"发票类型", en:"category",code:"C021"},
];
let data_dic = dataDic.map((data)=>{
    return {
        c_name:data.cn,
        e_name:data.en,
        isManage:data.isManage,
        columns:[{
            title:data.cn+"编号",
            dataIndex:"catCode",
            key:"catCode"
        },{
            title:data.cn+"名称",
            dataIndex:"catName",
            key:"catName"
        },{
            title:data.cn+"描述",
            dataIndex:"catDesc",
            key:"catDesc"
        }],
        inputs:[],
        code:data.code,
        tableData:"subject",
        fields:{
            code:"catCode",
            name:"catName",
            desc:"catDesc"
        }
    }
});
export const base_config = [...data_dic,{
        c_name:"国家",
        e_name:"country",
        columns:[{
            title:"国家编号",
            dataIndex:"countryCode",
            key:"countryCode"
        },{
            title:"国家名称",
            dataIndex:"countryName",
            key:"countryName"
        },{
            title:"国家描述",
            dataIndex:"countryDesc",
            key:"countryDesc"
        }],
        inputs:[],
        fields:{
            code:"countryCode",
            name:"countryName",
            desc:"countryDesc"
        }
    },{
        c_name:"地区",
        e_name:"region",
        columns:[{
            title:"地区编号",
            dataIndex:"regionCode",
            key:"regionCode"
        },{
            title:"国家名称",
            dataIndex:"countryName",
            key:"countryName"
        },{
            title:"地区名称",
            dataIndex:"regionName",
            key:"regionName"
        },{
            title:"地区描述",
            dataIndex:"regionDesc",
            key:"regionDesc"
        }],
        inputs:[{
            label:"所属国家",
            selectType:"country",
            optionName:"countryName",
            optionCode:"countryCode",
            handleChange:"setRegion"
        }],
        fields:{
            code:"regionCode",
            name:"regionName",
            desc:"regionDesc"
        }
    },{
        c_name:"省份",
        e_name:"province",
        columns:[{
            title:"省份编号",
            dataIndex:"provinceCode",
            key:"provinceCode"
        },{
            title:"国家名称",
            dataIndex:"countryName",
            key:"countryName"
        },{
            title:"地区名称",
            dataIndex:"regionName",
            key:"regionName"
        },{
            title:"省份名称",
            dataIndex:"provinceName",
            key:"provinceName"
        },{
            title:"省份描述",
            dataIndex:"provinceDesc",
            key:"provinceDesc"
        }],
        inputs:[{
            label:"所属国家",
            selectType:"country",
            optionName:"countryName",
            optionCode:"countryCode",
            handleChange:"setRegion"
        },{
            label:"所属地区",
            selectType:"region",
            optionName:"regionName",
            optionCode:"regionCode",
            handleChange:"setProvince"
        }],
        fields:{
            code:"provinceCode",
            name:"provinceName",
            desc:"provinceDesc"
        }
    },{
        c_name:"城市",
        e_name:"city",
        columns:[{
            title:"城市编号",
            dataIndex:"cityCode",
            key:"cityCode"
        },{
            title:"国家名称",
            dataIndex:"countryName",
            key:"countryName"
        },{
            title:"地区名称",
            dataIndex:"regionName",
            key:"regionName"
        },{
            title:"省份名称",
            dataIndex:"provinceName",
            key:"provinceName"
        },{
            title:"城市名称",
            dataIndex:"cityName",
            key:"cityName"
        },{
            title:"城市描述",
            dataIndex:"cityDesc",
            key:"cityDesc"
        }],
        inputs:[{
            label:"所属国家",
            selectType:"country",
            optionName:"countryName",
            optionCode:"countryCode",
            handleChange:"setRegion"
        },{
            label:"所属地区",
            selectType:"region",
            optionName:"regionName",
            optionCode:"regionCode",
            handleChange:"setProvince"
        },{
            label:"所属省",
            selectType:"province",
            optionName:"provinceName",
            optionCode:"provinceCode",
            handleChange:"setCity"
        }],
        fields:{
            code:"cityCode",
            name:"cityName",
            desc:"cityDesc"
        }
    },{
        c_name:"区县",
        e_name:"county",
        columns:[{
            title:"区县编号",
            dataIndex:"countyCode",
            key:"countyCode"
        },{
            title:"国家名称",
            dataIndex:"countryName",
            key:"countryName"
        },{
            title:"地区名称",
            dataIndex:"regionName",
            key:"regionName"
        },{
            title:"省份名称",
            dataIndex:"provinceName",
            key:"provinceName"
        },{
            title:"城市名称",
            dataIndex:"cityName",
            key:"cityName"
        },{
            title:"区县名称",
            dataIndex:"countyName",
            key:"countyName"
        },{
            title:"区县描述",
            dataIndex:"countyDesc",
            key:"countyDesc"
        }],
        inputs:[{
            label:"所属国家",
            selectType:"country",
            optionName:"countryName",
            optionCode:"countryCode",
            handleChange:"setRegion"
        },{
            label:"所属地区",
            selectType:"region",
            optionName:"regionName",
            optionCode:"regionCode",
            handleChange:"setProvince"
        },{
            label:"所属省份",
            selectType:"province",
            optionName:"provinceName",
            optionCode:"provinceCode",
            handleChange:"setCity"
        },{
            label:"所属市区",
            selectType:"city",
            optionName:"cityName",
            optionCode:"cityCode",
            handleChange:"setCity"
        }],
        fields:{
            code:"countyCode",
            name:"countyName",
            desc:"countyDesc"
        }
    },{
        c_name:"币种",
        e_name:"currency",
        columns:[{
            title:"币种编号",
            dataIndex:"curCode",
            key:"curCode"
        },{
            title:"币种名称",
            dataIndex:"curName",
            key:"curName"
        },{
            title:"货币符号",
            dataIndex:"symbol",
            key:"symbol"
        },{
            title:"本位币",
            dataIndex:"standardCoin",
            key:"standardCoin"
        },{
            title:"币种描述",
            dataIndex:"curDesc",
            key:"curDesc"
        }],
        inputs:[{
            label:"货币符号",
            control:"text",
            optionCode:"symbol"
        },{
            label:"本位币",
            optionCode:"standardCoin",
            enum:"baseDataStandardCoin"
        }],
        fields:{
            code:"curCode",
            name:"curName",
            desc:"curDesc"
        }
    },{
        c_name:"计量单位",
        e_name:"measure",
        isManage:1,
        columns:[{
            title:"计量单位编号",
            dataIndex:"meaCode",
            key:"meaCode"
        },{
            title:"计量单位名称",
            dataIndex:"meaName",
            key:"meaName"
        },{
            title:"计量维度",
            dataIndex:"dimensionality",
            key:"dimensionality"
        },{
            title:"单位符号",
            dataIndex:"symbol",
            key:"symbol"
        },{
            title:"计量单位描述",
            dataIndex:"meaDesc",
            key:"meaDesc"
        }],
        inputs:[{
            label:"计量维度",
            optionName:"dimensionality",
            optionCode:"dimensionality",
            enum:"baseDataDimensionality"
        },{
            label:"符号",
            control:"text",
            optionCode:"symbol"
        }],
        fields:{
            code:"meaCode",
            name:"meaName",
            desc:"meaDesc"
        }
    },
    {
        c_name:"业务",
        e_name:"business",
        columns:[{
            title:"业务类型",
            dataIndex:"busCode",
            key:"busCode"
        },{
            title:"业务类型",
            dataIndex:"busName",
            key:"busName"
        },{
            title:"业务类型",
            dataIndex:"busDesc",
            key:"busDesc"
        }],
        inputs:[],
        fields:{
            code:"busCode",
            name:"busName",
            desc:"busDesc"
        }
    },{
        c_name:"库存",
        e_name:"inventory",
        columns:[{
            title:"库存编号",
            dataIndex:"invCode",
            key:"invCode"
        },{
            title:"库存名称",
            dataIndex:"invName",
            key:"invName"
        },{
            title:"库存描述",
            dataIndex:"invDesc",
            key:"invDesc"
        }],
        inputs:[],
        fields:{
            code:"invCode",
            name:"invName",
            desc:"invDesc"
        }
    }
];